[tool.poetry]
name = "pyxlander"
version = "0.1.0"
description = ""
authors = ["JnyJny <erik.oshaughnessy@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
twod = ""

[tool.poetry.dev-dependencies]
pytest = "^3.0"
pytest-cov = ""

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
